# Generated by Django 5.2 on 2025-05-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanage1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='profile',
            name='flask_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
