# Generated by Django 5.2 on 2025-05-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanage1', '0002_alter_event_options_profile_flask_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
