# Generated by Django 5.2 on 2025-05-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventmanage1', '0004_event_flask_id_alter_event_date_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flask_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
