# Generated by Django 5.2 on 2025-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabbooking',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
